/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp data/com.georgefb.quickaccess.xml -a m.h
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef M_H
#define M_H

#include <QtCore/QObject>
#include <QtCore/QMetaObject>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Adaptor class for interface com.georgefb.QuickAccess
 */
class QuickAccessAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.georgefb.QuickAccess")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.georgefb.QuickAccess\">\n"
"    <method name=\"showMenu\"/>\n"
"    <method name=\"showMenu\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"pos\"/>\n"
"    </method>\n"
"    <method name=\"showDelayedMenu\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"delay\"/>\n"
"    </method>\n"
"    <method name=\"showDelayedMenu\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"delay\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"pos\"/>\n"
"    </method>\n"
"    <method name=\"showDelayedMenu\"/>\n"
"  </interface>\n"
        "")
public:
    QuickAccessAdaptor(QObject *parent);
    virtual ~QuickAccessAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void showDelayedMenu();
    void showDelayedMenu(int delay, int pos);
    void showDelayedMenu(int delay);
    void showMenu(int pos);
    void showMenu();
Q_SIGNALS: // SIGNALS
};

#endif
/*
 * Implementation of adaptor class QuickAccessAdaptor
 */

QuickAccessAdaptor::QuickAccessAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

QuickAccessAdaptor::~QuickAccessAdaptor()
{
    // destructor
}

void QuickAccessAdaptor::showDelayedMenu()
{
    // handle method call com.georgefb.QuickAccess.showDelayedMenu
    QMetaObject::invokeMethod(parent(), "showDelayedMenu");
}

void QuickAccessAdaptor::showDelayedMenu(int delay, int pos)
{
    // handle method call com.georgefb.QuickAccess.showDelayedMenu
    QMetaObject::invokeMethod(parent(), "showDelayedMenu", Q_ARG(int, delay), Q_ARG(int, pos));
}

void QuickAccessAdaptor::showDelayedMenu(int delay)
{
    // handle method call com.georgefb.QuickAccess.showDelayedMenu
    QMetaObject::invokeMethod(parent(), "showDelayedMenu", Q_ARG(int, delay));
}

void QuickAccessAdaptor::showMenu(int pos)
{
    // handle method call com.georgefb.QuickAccess.showMenu
    QMetaObject::invokeMethod(parent(), "showMenu", Q_ARG(int, pos));
}

void QuickAccessAdaptor::showMenu()
{
    // handle method call com.georgefb.QuickAccess.showMenu
    QMetaObject::invokeMethod(parent(), "showMenu");
}

